#!/usr/bin/env python3
"""
setup_env.py
Helper script for initial project setup of fam-ex backend.
Allows developers/operators to configure environment settings and choose between:
1) Local SQLite Database (aiosqlite)
2) Remote/Local PostgreSQL Database (asyncpg - Supabase / Aiven / Local Docker)
"""

import os
import secrets
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / ".env"
EXAMPLE_ENV = BASE_DIR / ".env.example"

DEFAULT_CORS_ORIGINS = "http://localhost:8080,http://127.0.0.1:8080,http://localhost:3000"

def print_banner():
    print("=" * 60)
    print("      fam-ex Backend Project Setup & Database Configuration   ")
    print("=" * 60)

def prompt_db_choice(default_choice="1"):
    print("\nSelect Database Storage Option for initial setup:")
    print("  [1] Local SQLite Database (embedded, file-based: ./data/fam_ex.db)")
    print("  [2] PostgreSQL Database (Remote Supabase / Aiven / Local Postgres)")
    
    choice = input(f"Enter choice [1 or 2] (default: {default_choice}): ").strip()
    if not choice:
        choice = default_choice
    return choice

def setup_sqlite():
    print("\n--- Configuring SQLite Database ---")
    db_file = input("Enter SQLite DB file path (default: ./data/fam_ex.db): ").strip()
    if not db_file:
        db_file = "./data/fam_ex.db"
    
    # Ensure data directory exists
    data_dir = BASE_DIR / "data"
    data_dir.mkdir(exist_ok=True)
    
    return {
        "DATABASE_TYPE": "sqlite",
        "SQLITE_DB_FILE": db_file,
    }

def setup_postgres():
    print("\n--- Configuring PostgreSQL (Supabase / Aiven / Local) ---")
    server = input("Postgres Host / Server (default: localhost): ").strip() or "localhost"
    port = input("Postgres Port (default: 5432): ").strip() or "5432"
    user = input("Postgres User (default: postgres): ").strip() or "postgres"
    password = input("Postgres Password (leave blank to auto-generate): ").strip()
    if not password:
        password = secrets.token_hex(16)
        print(f"[INFO] Generated random Postgres password: {password}")
    dbname = input("Postgres Database Name (default: fam_ex): ").strip() or "fam_ex"
    ssl = input("Require SSL? (true/false) (default: false): ").strip().lower() or "false"
    
    return {
        "DATABASE_TYPE": "postgres",
        "POSTGRES_SERVER": server,
        "POSTGRES_PORT": port,
        "POSTGRES_USER": user,
        "POSTGRES_PASSWORD": password,
        "POSTGRES_DB": dbname,
        "POSTGRES_SSL": ssl,
    }

def prompt_cors_origins():
    print("\n--- Configuring CORS Allowed Origins ---")
    print("Local dev origins (Web target) are always included:")
    print(f"  {DEFAULT_CORS_ORIGINS}")
    domains = input(
        "Enter production frontend domain(s) to allow, comma-separated\n"
        "(e.g. https://app.fam-ex.com) — leave blank if not deploying yet: "
    ).strip()

    origins = [DEFAULT_CORS_ORIGINS]
    if domains:
        origins.append(domains)
    else:
        print("[WARN] No production domain provided — only local dev origins will be allowed.")
        print("       Re-run this script or set CORS_ORIGINS in .env before deploying.")
    return ",".join(origins)

def write_env_file(config: dict):
    # SECRET_KEY env var lets automated/repeat runs (e.g. a redeploy) pin a stable key;
    # otherwise generate a fresh random one so we never ship a well-known placeholder
    # into a real deployment's JWT signing key.
    secret_key = os.getenv("SECRET_KEY") or secrets.token_hex(32)

    env_content = [
        "# Generated by scripts/setup_env.py for fam-ex Backend",
        'PROJECT_NAME="fam-ex Backend"',
        "DEBUG=True",
        'API_V1_STR="/api/v1"',
        f'SECRET_KEY="{secret_key}"',
        "ACCESS_TOKEN_EXPIRE_MINUTES=10080",
        f"CORS_ORIGINS={config['CORS_ORIGINS']}",
        "",
        f"DATABASE_TYPE={config['DATABASE_TYPE']}",
    ]
    
    if config["DATABASE_TYPE"] == "sqlite":
        env_content.append(f"SQLITE_DB_FILE={config['SQLITE_DB_FILE']}")
    else:
        env_content.append(f"POSTGRES_SERVER={config['POSTGRES_SERVER']}")
        env_content.append(f"POSTGRES_PORT={config['POSTGRES_PORT']}")
        env_content.append(f"POSTGRES_USER={config['POSTGRES_USER']}")
        env_content.append(f"POSTGRES_PASSWORD={config['POSTGRES_PASSWORD']}")
        env_content.append(f"POSTGRES_DB={config['POSTGRES_DB']}")
        env_content.append(f"POSTGRES_SSL={config['POSTGRES_SSL']}")
        
    with open(ENV_FILE, "w") as f:
        f.write("\n".join(env_content) + "\n")
        
    print(f"\n[SUCCESS] Configuration saved to: {ENV_FILE}")

def main():
    print_banner()
    
    # Non-interactive mode via arguments
    if len(sys.argv) > 1:
        mode = sys.argv[1].lower()
        if mode == "sqlite":
            config = setup_sqlite_non_interactive()
        elif mode == "postgres":
            config = setup_postgres_non_interactive()
        else:
            print(f"Unknown mode '{mode}'. Use 'sqlite' or 'postgres'.")
            sys.exit(1)
        config["CORS_ORIGINS"] = os.getenv("CORS_ORIGINS", DEFAULT_CORS_ORIGINS)
    else:
        choice = prompt_db_choice()
        if choice == "2":
            config = setup_postgres()
        else:
            config = setup_sqlite()
        config["CORS_ORIGINS"] = prompt_cors_origins()

    write_env_file(config)

def setup_sqlite_non_interactive():
    data_dir = BASE_DIR / "data"
    data_dir.mkdir(exist_ok=True)
    return {
        "DATABASE_TYPE": "sqlite",
        "SQLITE_DB_FILE": "./data/fam_ex.db",
    }

def setup_postgres_non_interactive():
    password = os.getenv("POSTGRES_PASSWORD")
    if not password:
        password = secrets.token_hex(16)
        print(f"[INFO] POSTGRES_PASSWORD not set — generated a random one: {password}")
    return {
        "DATABASE_TYPE": "postgres",
        "POSTGRES_SERVER": os.getenv("POSTGRES_SERVER", "localhost"),
        "POSTGRES_PORT": os.getenv("POSTGRES_PORT", "5432"),
        "POSTGRES_USER": os.getenv("POSTGRES_USER", "postgres"),
        "POSTGRES_PASSWORD": password,
        "POSTGRES_DB": os.getenv("POSTGRES_DB", "fam_ex"),
        "POSTGRES_SSL": os.getenv("POSTGRES_SSL", "false"),
    }

if __name__ == "__main__":
    main()
