"""enforce one household membership per user

Revision ID: 6ec7c455842b
Revises: f65692d4add0
Create Date: 2026-07-29 21:06:08.499093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec7c455842b'
down_revision: Union[str, None] = 'f65692d4add0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_household_members_user_id'), 'household_members', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_household_members_user_id'), table_name='household_members')
    # ### end Alembic commands ###
