"""add missing household_id indexes

Revision ID: 7e4675cad365
Revises: 448438686134
Create Date: 2026-07-30 11:03:47.708840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4675cad365'
down_revision: Union[str, None] = '448438686134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_categories_household_id', 'categories', ['household_id'], unique=False)
    op.create_index('ix_invites_household_id', 'invites', ['household_id'], unique=False)
    op.create_index('ix_transactions_household_id_created_at', 'transactions', ['household_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_household_id_created_at', table_name='transactions')
    op.drop_index('ix_invites_household_id', table_name='invites')
    op.drop_index('ix_categories_household_id', table_name='categories')
    # ### end Alembic commands ###
