"""add transaction indexes for household_id and category_id

Revision ID: c97b8f0e262b
Revises: e2eaf9009180
Create Date: 2026-07-29 18:33:32.665921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97b8f0e262b'
down_revision: Union[str, None] = '74dd4ff7da5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_category_id', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_household_id_transaction_date', 'transactions', ['household_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_household_id_transaction_date', table_name='transactions')
    op.drop_index('ix_transactions_category_id', table_name='transactions')
    # ### end Alembic commands ###
